---
# Project information
site_name: Bibi40k | home-infrastructure
site_description: My home infrastructure documentation
site_author: Bɪʙɪ40ᴋ
site_url: https://Bibi40k.github.io/home-infrastructure/

# Repository
repo_name: Bibi40k/home-infrastructure
repo_url: https://github.com/Bibi40k/home-infrastructure
edit_uri: ""

# Configuration
docs_dir: ./docs

theme:
  name: material
  logo: _assets/images/logo.jpg
  icon:
    repo: fontawesome/brands/github-alt
  language: en
  font: false
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: blue grey
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Plugins
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - macros:
      include_dir: docs/_snippets

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true

# Customization
extra_javascript:
  - _assets/js/fancybox.umd.js

extra_css:
  - _assets/css/fancybox.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Bibi40k

# Navigation structure
nav:
  - Home:
      - "index.md"
      - "home/repo_structure.md"
      - "home/cluster_overview.md"
      - "home/tools.md"
  - Storage:
      - "storage/index.md"
      - "storage/backups.md"
  - Networking:
      - "networking/index.md"
      - "networking/dns.md"
      - "networking/podgateway.md"
      - "networking/multus.md"